import type { ServiceAreaArticle } from "./types";

export const sunriseArticle: ServiceAreaArticle = {
  slug: "sunrise",
  title: "Sunrise Real Estate Guide in Puyallup, WA",
  excerpt:
    "Sunrise is Pierce County's master-planned community on Puyallup's South Hill — plats between 152nd and 198th east of Meridian, with parks, a county development agreement, and school assignment that a citywide average misses.",
  updatedAt: "2026-10-10",
  bodyMarkdown: `Sunrise is the Pierce County master-planned community on Puyallup's South Hill. The [county's Sunrise development page](https://www.piercecountywa.gov/5716/Sunrise) describes about 1,467 acres between 152nd Street East and 198th Street East, roughly four miles south of SR 512 and one mile east of Meridian (SR 161), in the Thun Field area. Buyers comparing this pocket to the broader [South Hill](/service-areas/puyallup/south-hill) bench, established streets in [Gem Heights](/service-areas/puyallup/gem-heights), view lots on [Shawnee Ridge](/service-areas/puyallup/shawnee-ridge), or the valley floor in [Downtown Puyallup](/service-areas/puyallup/downtown-puyallup) should underwrite by Sunrise plats first, not a citywide median. The parent map is the [Puyallup](/service-areas/puyallup) hub. Active search usually starts with [Puyallup homes for sale](/listings?city=Puyallup&state=WA).

The same county page traces the project to a 1983 application for the Rainier Terrace Master Planned Community, later entitled as Sunrise. A development agreement sets the zoning and infrastructure expectations inside the master plan, and the county publishes critical-area, sewer, storm, and road maps with that file. Daily routes organize around Sunrise Boulevard and Sunrise Parkway, [122nd Avenue East](https://www.piercecountywa.gov/8432/122nd-Avenue-East-Corridor-CRPs-5786-589), and the east–west streets from 152nd through 198th. The county describes several neighborhood parks, a community center and park along Sunrise Boulevard in the northern part of the plan, and a regional park at the southwest corner of 122nd and Sunrise Boulevard, along with walking paths and Mount Rainier view corridors. Retail and services along Meridian, including [South Hill Mall](https://www.southhillmall.com/), sit just west of the master plan. Check the county page for which phases are built and which are still in review — that status moves with each five-year update.

Housing here is master-plan product, not one era or one lot size. Pierce County describes a mix of single-family and multi-family development, including a medical campus inside the plan. Treat interior courts, boulevard frontage, and multi-family parcels as related but not identical micro-comp sets. Many divisions are covered by association documents — confirm CC&Rs and any resale certificate for the specific plat rather than assuming every Sunrise address has the same dues or amenities. Do not price these streets off downtown 98371 or off a generic South Hill average. Documented campus and boulevard addresses in this pocket use ZIP 98374; confirm the parcel ZIP, because South Hill postal codes change by street.

Schools need an address, not a neighborhood name. The [Puyallup School District](https://www.puyallupsd.org/) places [Emerald Ridge High School](https://erhs.puyallupsd.org/) and [Glacier View Junior High](https://gvjh.puyallupsd.org/about-us/building-history) on the district's Sunrise campus inside the master plan, east of Meridian. Elementary campuses buyers often check from here include [Pope Elementary](https://pop.puyallupsd.org/), just north of 152nd Street East, and [Edgerton Elementary](https://edg.puyallupsd.org/). The district has also noted that most homes fall in Puyallup schools while some planned edge neighborhoods sit in the [Orting School District](https://www.ortingschools.org/) — confirm the parcel before you write an offer. Campus history is on the [district building-history pages](https://www.puyallupsd.org/about-us/building-history).

Permits for the master plan run through Pierce County, not automatically through the City of Puyallup. Start with the county Sunrise page for the development agreement, critical-area maps, sewer maps, and utility agreements, then confirm taxes, lot dimensions, and assessed value with the [Pierce County Assessor-Treasurer](https://www.piercecountywa.gov/91/Assessor---Treasurer). Electric and natural gas commonly come from [Puget Sound Energy](https://www.pse.com/). If a lot is not on the county sewer system, use the [Tacoma–Pierce County Health Department](https://www.tpchd.org/) and our [Pierce County septic systems guide](/blog/pierce-county-septic-systems-what-homebuyers-and-sellers-must-know-in-todays-market). The [Pierce County Library — South Hill](https://www.piercecountylibrary.org/locations/southhilllibrary.htm) is the nearby branch. Active and sold context typically runs through [NWMLS](https://www.nwmls.com/) — compare Sunrise plats to Sunrise plats.

Living in Sunrise is about matching a specific plat to schools, master-plan rules, and Meridian access you will actually use. Whether you are selling a long-held home on Sunrise Boulevard or buying into a later phase near 184th, André and Cindie Bohall at OnSite Real Estate Group focus on micro-neighborhood comps, association and critical-area paperwork, and school assignment by address. When you are ready, browse [Puyallup homes for sale](/listings?city=Puyallup&state=WA) or [start a conversation with our team](/contact-us?area=Sunrise&topic=selling).`,
};
