import type { ServiceAreaArticle } from "./types";

export const tacomaArticle: ServiceAreaArticle = {
  slug: "tacoma",
  title: "Buying, Selling, and Living in Tacoma, WA",
  excerpt:
    "What buying, selling, and living in Tacoma really involves — North End, Proctor, Stadium, and West Slope micro-markets, Tacoma Public Schools, historic overlays, ADU/infill rules, and urban commute patterns.",
  updatedAt: "2026-08-28",
  bodyMarkdown: `Tacoma is Pierce County's urban core — a block-by-block market where North End, Proctor, Stadium District, West Slope, and South Tacoma can price and show like different cities even when the ZIP codes sit a few miles apart. Buyers comparing [Tacoma homes for sale](/listings?city=Tacoma&state=WA) often cross-shop [Puyallup](/service-areas/puyallup), [Federal Way](/service-areas/federal-way), and [Lake Tapps](/service-areas/lake-tapps) while underwriting Tacoma on micro-location, not a citywide average. The [City of Tacoma Planning & Development Services](https://www.cityoftacoma.org/government/city_departments/planning_and_development_services) is the practical starting point for permits, design review, and code compliance inside city limits.

North End and Proctor lean toward established single-family streets, craftsmanship-era homes, and walkable access to neighborhood retail. Stadium District and downtown-adjacent blocks add denser housing, event-calendar parking realities, and a mix of historic character with newer infill. West Slope and hillside corridors often trade flat-yard convenience for territorial and Sound views, while South Tacoma and other mid-city pockets can deliver more approachable price points with different buyer profiles. Those differences show up in comps, days on market, and how sellers should stage — which is why listing strategy belongs to the district, not the municipal boundary.

Historic conservation districts and neighborhood overlays change what you can do to a facade, porch, or addition. Before marketing "renovation potential" or budgeting exterior work, confirm overlay status and design-review expectations with city planning. Tacoma's infill and ADU allowances also shape highest-and-best-use conversations on larger lots — a duplex, ADU, or lot-split story only works if the code path and parking rules support it.

Utilities are usually municipal through [Tacoma Public Utilities](https://www.mytpu.org/) for power and water, with natural gas commonly from [Puget Sound Energy](https://www.pse.com/) in many neighborhoods. Older homes may need panel, lateral, or meter notes before a remodel scope is final; pull service records early so inspection surprises do not stall escrow. For parcel history, assessed value, and tax detail, use the [Pierce County Assessor-Treasurer](https://www.piercecountywa.gov/91/Assessor---Treasurer).

Schools are a frequent filter for relocating families. [Tacoma Public Schools](https://www.tacomaschools.org/) covers the city as Washington's third-largest district, but attendance boundaries and program options still vary by address — confirm assignment for each property rather than assuming a North End or Proctor label equals a specific campus. Everyday community resources include [Tacoma Public Library](https://www.tacomalibrary.org/) branches across the North End, Proctor, and South Tacoma, plus chamber and civic networks through the [Tacoma-Pierce County Chamber](https://www.tacomachamber.org/).

Commute and lifestyle patterns split by corridor. I-5, SR-16, and the Tacoma Dome / Sounder / Link transit spine shape how buyers weigh downtown-adjacent living versus West Slope access toward Gig Harbor or mid-city routes toward [Puyallup](/service-areas/puyallup) and the East Pierce plateau. Street parking, event nights near Stadium and the Dome, and urban contractor windows all matter for showing logistics and seller prep calendars. For wider Pierce County trend context after the frenzy years, see our [Pierce County housing market overview](/blog/pierce-county-housing-market-what-stability-really-looks-like-after-the-frenzy); hybrid and remote work continue to reshape which Tacoma pockets buyers prioritize, a theme we cover in [how remote work continues to shape buyer patterns](/blog/how-remote-work-continues-to-shape-buyer-patterns-in-pierce-county).

Active and sold context typically runs through [NWMLS](https://www.nwmls.com/) — compare North End, Proctor, Stadium, West Slope, and South Tacoma like-for-like rather than one Tacoma average. Living in Tacoma is about matching a specific district's housing stock, overlay rules, schools, and commute to how you actually want to live day to day. Whether you are selling a long-held North End bungalow or buying near Proctor with walkable amenities, André and Cindie Bohall at OnSite Real Estate Group focus on micro-market comps, permit diligence, and urban logistics so decisions match everyday reality. When you are ready, browse [Tacoma homes for sale](/listings?city=Tacoma&state=WA) or [start a conversation with our team](/contact-us?area=Tacoma&topic=selling).`,
};
